"""Added tracks_saved column to User, title to Track

Revision ID: bbd74ffc30ef
Revises: cfb6f101d2df
Create Date: 2026-08-26 17:26:19.765594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bbd74ffc30ef'
down_revision: Union[str, None] = 'cfb6f101d2df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_posts_id', table_name='posts')
    op.drop_table('posts')
    op.add_column('tracks', sa.Column('title', sa.String(), nullable=True))
    op.add_column('tracks', sa.Column('creator_id', sa.Integer(), nullable=False))
    op.drop_column('tracks', 'creator_email')
    op.add_column('users', sa.Column('tracks_saved', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tracks_saved')
    op.add_column('tracks', sa.Column('creator_email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('tracks', 'creator_id')
    op.drop_column('tracks', 'title')
    op.create_table('posts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('uploader_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('posted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('audio_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('likes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='posts_pkey')
    )
    op.create_index('ix_posts_id', 'posts', ['id'], unique=False)
    # ### end Alembic commands ###
